# Generated by Django 4.2.2 on 2024-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/%Y/%m/%d', verbose_name='File')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['-uploaded'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='Word')),
                ('count_of_documents', models.IntegerField(default=1, verbose_name='Count of documents with the word')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['word'],
                'indexes': [models.Index(fields=['word'], name='analysis_wo_word_ed66ce_idx')],
            },
        ),
    ]
